#!/bin/bash

# Set some defaults if environment variables haven't been provided
MONGO_HOSTS=${MONGO_HOSTS:='Performance/machine06,machine08,machine09'}
MONGO_USER=${MONGO_USER:=spotxde}
MONGO_PASS=${MONGO_PASS:=password}

mongo --quiet --username $MONGO_USER --password=$MONGO_PASS --host $MONGO_HOSTS ltrx --eval "print(db.services.distinct('ltrx.node_id'))" | remove-mongo-cruft | tr ',' ' '
