#!/bin/bash

export GIT_NAME_VANTRIX="Chuck Wilson"
export GIT_EMAIL_VANTRIX="charles.wilson@vantrix.com"
export GIT_NAME_GITHUB="Chuck Wilson"
export GIT_EMAIL_GITHUB="chuck.wilson+github@gmail.com"

