#!/bin/bash
embed-tmux() {
    VER="$(tmux -V)"
    printf '\033]2;%s\033\\' "$VER"
    export EMBEDDED=1
    TEMP=${TMUX%*,*}
    export TMUX_MASTER=${TEMP%*,*}
    tmux -L "$1" has-session -t "LOCAL" && tmux -L "$1" attach -t "LOCAL" || tmux -L "$1" new-session -s "LOCAL"
}

if [ -n "$1" ]; then
    # We're being called as a script, rather than just being sourced
    embed-tmux "$@"
fi
