#!/bin/bash

alias bash="bash --rcfile ~/$DOTFILES/bash/bashrc"
alias screen="screen -c ~/$DOTFILES/screen/screenrc"
alias tmux="tmux -f ~/$DOTFILES/tmux/tmux.conf"
export WEECHAT_HOME=~/$DOTFILES/weechat/
