#!/bin/bash
start-remote-env() {
    SCRIPTFILE=${SCRIPTFILE:=https://raw.githubusercontent.com/squarebracket/dotfiles/master/setup-environment.sh}
    SERVER=$1
    LAUNCH_SHELL=${2:=$SHELL}
    REMOTE_USER=$USER
    LOOPBACK_PORT=5555
    echo -e "    Launching remote environment for $ENVIRONMENT"
    while [ true ]; do
        VARS_TO_PASS="ENVIRONMENT=$ENVIRONMENT POWERLINE_FONT=$POWERLINE_FONT LOOPBACK_PORT=$LOOPBACK_PORT"
        ssh -R "$LOOPBACK_PORT":localhost:22 -o ExitOnForwardFailure=yes $SERVER -t "wget --no-check-certificate $SCRIPTFILE -O .setup_env.sh && $VARS_TO_PASS bash .setup_env.sh $USER $LAUNCH_SHELL"
        EXIT_CODE=$?
        if [ $EXIT_CODE = 13 ]; then
            # We need to get the remote server's SSH key
            echo "    Need to install server's SSH key locally"
            echo "$(ssh -q $2 -t 'cat ~/.ssh/id_rsa.pub')" >> ~/.ssh/authorized_keys
        elif [ $EXIT_CODE = 0 ]; then
            echo "    Exiting normally"
            return 0
        elif [ $EXIT_CODE = 255 ]; then
            LOOPBACK_PORT=$(($LOOPBACK_PORT+1))
            [ $LOOPBACK_PORT = 5565 ] && echo "    ERROR: Ports 5555-5565 were all used. Exiting." && exit 1
            echo "    Exit code was $EXIT_CODE, trying port $LOOPBACK_PORT"
        fi
    done
}

if [ -n "$1" ]; then
    # We're being called as a script, rather than just being sourced
    start-remote-env "$@"
fi
