#!/bin/bash

if [ -f /opt/deployment ]; then
    DEPLOYMENT=`cat /opt/deployment`
    MACHINE=`hostname -s`
    if [ "$DEPLOYMENT" = "soak1" ]; then
        DEPLOYMENT_COLOUR="\e[0;34m"
    elif [ "$DEPLOYMENT" = "soak2" ]; then
        DEPLOYMENT_COLOUR="\e[0;35m"
    elif [ "$DEPLOYMENT" = "soak3" ]; then
        DEPLOYMENT_COLOUR="\e[0;91m"
    fi
    PROMPT_COMMAND='hasjobs="$(jobs -p | wc -l)"; if [ "$hasjobs" -gt "0" ]; then echo -en "\e[0;31m$hasjobs\e[0m " ; fi'
    PS1="\[$DEPLOYMENT_COLOUR\]$DEPLOYMENT \[\e[0;36m\]$MACHINE\[\e[0m\] \w \[\e[0;36m\]\\$\[\e[0m\] "
fi
