#!/bin/bash

# required for powerline
if [ -z "$XDG_CONFIG_DIRS" ]; then
    export XDG_CONFIG_DIRS="~/$DOTFILES/config"
else
    export XDG_CONFIG_DIRS="${XDG_CONFIG_DIRS}:~/$DOTFILES/config"
fi
export PYTHONPATH="${PYTHONPATH}:~/$DOTFILES/config/powerline"
