# Path to your oh-my-zsh installation.
export ZSH=/home/chuck/.oh-my-zsh
alias s="xclip -in -sel clipboard < ~/.credentials/svn"

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
export DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
### These are all the plugins I want loaded, but it is quite a few. Probably best to load them in dynamically
#plugins=(bundler celery colored-man-pages colorize compleat cp django docker gem git git-extras gitfast github git-hubflow git-remote-branch gnu-utils jira jsontools mosh pip pow pyenv python rake rbenv ruby rvm screen sudo svn-fast-info vagrant virtualenv virtualenvwrapper yum)
plugins=(colorize cp gem git git-extras github git-remote-branch mosh pip python sudo svn-fast-info tmux virtualenv virtualenvwrapper yum)

# User configuration

export PATH="/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/chuck/.local/bin:/home/chuck/bin:/home/chuck/.rvm/bin:/home/chuck/vantrix-files/"
# export MANPATH="/usr/local/man:$MANPATH"

ZSH_TMUX_AUTOCONNECT=false
#ZSH_TMUX_AUTOSTART=true

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vimx'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias vim="vimx"
DEFAULT_USER=chuck

# Set the dotfiles directory
if [ -n "$REMOTE_USER" ]; then
    export DOTFILES=~/.dotfiles-$REMOTE_USER
else
    export DOTFILES=~/dotfiles
fi

# Auto-source files depending on environment
source $DOTFILES/zsh/sourcer

# Source oh-my-zsh and activate plugins
# This has to be done after you've autoloaded to make sure all plugins
# are collected.
source $ZSH/oh-my-zsh.sh


PATH="/home/chuck/perl5/bin${PATH+:}${PATH}"; export PATH;
PERL5LIB="/home/chuck/perl5/lib/perl5${PERL5LIB+:}${PERL5LIB}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/chuck/perl5${PERL_LOCAL_LIB_ROOT+:}${PERL_LOCAL_LIB_ROOT}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/chuck/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/chuck/perl5"; export PERL_MM_OPT;
